version: '3.8'

services:
  ubuntu:
    image: ubuntu:24.04
    volumes:
      - .:/workspace
      - /home/brabus/zig-bin:/bin/zig-bin
    working_dir: /workspace
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin/zig-bin
    stdin_open: true
    tty: true