version: '3'

vars:
  INSTANCES_YAML:
    sh: cat testing/instances.yaml
  INSTANCES:
    ref: fromYaml .INSTANCES_YAML
  INSTANCES_NAMES_JSON:
    sh: yq -o=json '.instances | keys' testing/instances.yaml
  INSTANCES_NAMES:
    ref: fromYaml .INSTANCES_NAMES_JSON
  SSHIPTS: '-i ~/.ssh/vagrant_ecdsa'

tasks:
  build-builder:
    desc: Build the Docker image
    sources:
      - Dockerfile
    cmds:
      - docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t miniminion-builder .

  build:
    desc: Build the miniminion project
    cmds:
      - docker run --rm -v .:/workspace -w /workspace miniminion-builder zig build -Doptimize=Debug --summary all
    sources:
      - src/**/*.zig
      - src/**/*.c
      - build.zig
    generates:
      - zig-out/bin/minim-agent
      - zig-out/bin/minim-controller
    deps:
      - build-builder

  test:
    desc: Run all tests
    cmds:
      - docker run --rm -v .:/workspace -w /workspace miniminion-builder zig test src/resource.zig -lc -static --name all-tests
    deps:
      - build-builder

  v-status:
    desc: 'Get status for vagrant instances'
    dir: './testing'
    cmd: 'vagrant status'

  v-up:*:
    vars:
      T: "{{ index .MATCH 0 }}"
      TARGETS: '{{if eq .T "all"}}{{.INSTANCES_NAMES | toJson}}{{else}}["{{.T}}"]{{end}}'
    desc: 'Up {{index .MATCH 0}} vagrant vm'
    dir: './testing'
    cmd: |
      {{range $index, $element := .TARGETS | fromJson}}
      vagrant up {{ $element }} &
      {{end}}
      wait

  v-destroy:*:
    vars:
      T: "{{ index .MATCH 0 }}"
      TARGETS: '{{if eq .T "all"}}{{.INSTANCES_NAMES | toJson}}{{else}}["{{.T}}"]{{end}}'
    desc: 'Destroy {{index .MATCH 0}} vagrant vm'
    dir: './testing'
    cmd: |
      {{range $index, $element := .TARGETS | fromJson}}
      vagrant destroy -f {{ $element }} &
      {{end}}
      wait

  v-ssh:*:
    desc: 'Login into {{index .MATCH 0}} vagrant vm'
    vars:
      VM_IP: '{{index .INSTANCES.instances (index .MATCH 0) "ip"}}'
    cmd: 'ssh root@{{.VM_IP}} {{.SSHIPTS}}'

  v-deploy:*:
    vars:
      T: "{{ index .MATCH 0 }}"
      TARGETS: '{{if eq .T "all"}}{{.INSTANCES_NAMES | toJson}}{{else}}["{{.T}}"]{{end}}'
    desc: 'Deploy to {{index .MATCH 0}} VM'
    cmds:
      - cmd: |
          {{range $index, $element := .TARGETS | fromJson}}
          IP={{index $.INSTANCES.instances $element "ip"}} NAME={{$element}}
          {{range (index $.INSTANCES.instances $element "deploy")}}
          {{.}} &
          {{end}}
          {{end}}
          wait
    failfast: true
    deps:
      - build

  v-redeploy:*:
    vars:
      T: "{{ index .MATCH 0 }}"
    desc: 'Recreate {{index .MATCH 0}} and deploy files'
    dir: './testing'
    cmds:
      - task: "v-destroy:{{ .T }}"
      - task: "v-up:{{ .T }}"
      - task: "v-deploy:{{ .T }}"
      - task: "v-run:{{ .T }}"
    deps:
      - build

  v-run:*:
    vars:
      T: "{{ index .MATCH 0 }}"
      TARGETS: '{{if eq .T "all"}}{{.INSTANCES_NAMES | toJson}}{{else}}["{{.T}}"]{{end}}'
    desc: 'Run on {{index .MATCH 0}} VM'
    cmds:
      - cmd: |
          {{range $index, $element := .TARGETS | fromJson}}
          IP={{index $.INSTANCES.instances $element "ip"}} NAME={{$element}}
          echo "{{index $.INSTANCES.instances $element "run"}}" | ssh root@$IP {{$.SSHIPTS}} &
          {{end}}
          wait