version: '3'

tasks:
  build-builder:
    desc: Build the Docker image
    sources:
      - Dockerfile
    cmds:
      - docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t miniminion-builder .

  build:
    desc: Build the miniminion project inside Zig container
    cmds:
      - docker run --rm -v .:/workspace -w /workspace miniminion-builder zig build -Doptimize=Debug
    sources:
      - src/**/*.zig
      - build.zig
    generates:
      - zig-out/bin/miniminion
    deps:
      - build-builder

  v-up:
    desc: Up vagrant vm
    dir: './testing/'
    cmd: vagrant up

  v-deploy:
    desc: Deploy miniminion binary and config to Vagrant VM
    cmds:
      - scp  -i ~/.ssh/vagrant_ecdsa ./zig-out/bin/miniminion root@192.168.56.2:/root/
      - scp  -i ~/.ssh/vagrant_ecdsa ./minim.jsonnet root@192.168.56.2:/root/
    failfast: true
    deps:
      - build
      # - v-up
  
  v-redeploy:
    desc: Recreate vm and deploy files
    dir: './testing'
    cmds:
      - task: v-destroy
      - task: v-deploy
      - task: v-run

  v-ssh:
    desc: Login into vagrant vm
    cmd: ssh root@192.168.56.2 -i ~/.ssh/vagrant_ecdsa
    # deps:
    #   - v-up

  v-run:
    desc: Run minim from vagrant vm
    cmd: "ssh root@192.168.56.2 -i ~/.ssh/vagrant_ecdsa -- /root/miniminion"

  v-destroy:
    desg: Destroy vagrant vm
    dir: './testing/'
    cmd: vagrant destroy -f

