require 'yaml'

env = ENV['ENV'] || 'k8s'
instances_yaml = File.join(__dir__, env, 'instances.yaml')

unless File.exist?(instances_yaml)
  raise "Environment '#{env}' not found: missing #{instances_yaml}"
end

instances = YAML.load_file(instances_yaml)['instances']

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/vagrant_ecdsa.pub").first.strip

  instances.each do |name, opts|
    config.vm.define name do |vm|
      vm.vm.box = opts['box']
      vm.vm.network "private_network", ip: opts['ip']
      vm.vm.hostname = name

      vm.vm.provision "shell" do |s|
        s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end

      vm.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = opts['memory']
        vb.cpus = opts['cpus']
      end
    end
  end
end